export const GET_LEVELS_ARR = 'GET_LEVELS_ARR';

export const SET_LEVELS_ARR = 'SET_LEVELS_ARR';

export const SET_SCORE_POINTS = 'SET_SCORE_POINTS';

export const GET_SCORE_POINTS = 'GET_SCORE_POINTS';